import type { Card, Contact } from "./types.ts";

export const EMOJI_CHOICES: readonly string[] = [
  "🦊",
  "💼",
  "🎭",
  "🚀",
  "🌸",
  "🎮",
  "🐙",
  "🎨",
  "⭐",
  "🦉",
  "🌊",
  "🔥",
];

export const SEED_CARDS: readonly Card[] = [
  {
    id: "c1",
    name: "Everyday",
    handle: "finnriver",
    avatar: "🦊",
    color: 0,
    tag: "Your main you",
    bio: "Coffee, cameras, and long walks. Sharing bits of daily life.",
    proofs: [
      { provider: "twitter", username: "@finnriver" },
      { provider: "github", username: "finnriver" },
      { provider: "reddit", username: "u/finnriver" },
      { provider: "email", username: "finn@hey.com" },
    ],
  },
  {
    id: "c2",
    name: "Work",
    handle: "finn.designs",
    avatar: "💼",
    color: 1,
    tag: "Professional",
    bio: "Product designer. Posting about craft, tools, and teams.",
    proofs: [
      { provider: "twitter", username: "@finn_designs" },
      { provider: "slack", username: "Acme HQ" },
      { provider: "confluence", username: "finn@acme" },
    ],
  },
  {
    id: "c3",
    name: "Anon",
    handle: "shadowfox",
    avatar: "🎭",
    color: 2,
    tag: "Just for lurking",
    bio: "",
    proofs: [],
  },
];

export const SEED_CONTACTS: readonly Contact[] = [
  {
    id: "p1",
    name: "Aria Wolfe",
    handle: "@ariawolfe",
    avatar: "🦋",
    color: 4,
    mutuals: 8,
    bio: "Illustrator & night owl. Drawing tiny worlds one pixel at a time.",
    proofs: [
      { provider: "twitter", username: "@ariawolfe" },
      { provider: "github", username: "ariawolfe" },
      { provider: "email", username: "aria@art.co" },
    ],
    npub: "npub1ar9…kf20q",
  },
  {
    id: "p2",
    name: "Milo Chen",
    handle: "@milo",
    avatar: "🐙",
    color: 3,
    mutuals: 12,
    bio: "Building thoughtful tools. Tea over coffee, always shipping.",
    proofs: [
      { provider: "github", username: "milochen" },
      { provider: "twitter", username: "@milo" },
      { provider: "confluence", username: "milo@lab" },
    ],
    npub: "npub1ml7…4kd9x",
  },
  {
    id: "p3",
    name: "Sana Okafor",
    handle: "@sana",
    avatar: "🌊",
    color: 1,
    mutuals: 5,
    bio: "Photographer chasing light. Prints & zines, occasionally.",
    proofs: [
      { provider: "twitter", username: "@sana" },
      { provider: "reddit", username: "u/sanaphoto" },
    ],
    npub: "npub1sn3…p8w2f",
  },
  {
    id: "p4",
    name: "Rune Halvorsen",
    handle: "@rune",
    avatar: "🔥",
    color: 5,
    mutuals: 3,
    bio: "Makes tiny internet projects. Bonfires and black coffee.",
    proofs: [
      { provider: "twitter", username: "@rune" },
      { provider: "reddit", username: "u/runenode" },
    ],
    npub: "npub1rn2…x6t7m",
  },
  {
    id: "p5",
    name: "Priya Nair",
    handle: "@priya",
    avatar: "🌸",
    color: 0,
    mutuals: 9,
    bio: "Writer. Threads about cities, food, and small everyday joys.",
    proofs: [
      { provider: "twitter", username: "@priya" },
      { provider: "facebook", username: "Priya Nair" },
      { provider: "email", username: "priya@words.io" },
    ],
    npub: "npub1pr5…m1v8s",
  },
];
